### PR TITLE
Reduce static memory usage

### PR DESCRIPTION
**Pull request by d-a-v**
Compilation results of 'Advanced' example on esp8266:

Before:
```
IROM   : 314364          - code in flash         (default or ICACHE_FLASH_ATTR)
IRAM   : 28480   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...)
DATA   : 1280  )         - initialized variables (global, static) in RAM/HEAP
RODATA : 2096  ) / 81920 - constants             (global, static) in RAM/HEAP
BSS    : 27608 )         - zeroed variables      (global, static) in RAM/HEAP
```

After:
```
IROM   : 314092          - code in flash         (default or ICACHE_FLASH_ATTR)
IRAM   : 28480   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...)
DATA   : 1280  )         - initialized variables (global, static) in RAM/HEAP
RODATA : 2096  ) / 81920 - constants             (global, static) in RAM/HEAP
BSS    : 27280 )         - zeroed variables      (global, static) in RAM/HEAP
```

### CODE REVIEW

**Comment by Juerd** [comment]
Thanks again!

I think you laid bare a more fundamental issue: those variables don't need to be static at all! Looking back I think I've made them static either because I had different plans for portal() or to be lazy and capture them implicitly for the lambdas.

With static pointers and then creating the objects at runtime, basically the objects themselves are no longer static and the only remaining use for `static` is a hack to save a tiny bit of code down the road (they can be excluded from the lamda captures).

I'll just turn these variables into regular function scoped variables, which should have the same effect as your PR plus a few more bytes for the pointers :P

As an aside, I get much smaller numbers for the Advanced.ino example (changed to use LittleFS),

```
IROM   : 301532          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27424   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1256  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1992  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25696 )         - zeroed variables      (global, static) in RAM/HEAP 

captures:
IROM   : 301324          - code in flash         (default or ICACHE_FLASH_ATTR)
IRAM   : 27424   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...)
DATA   : 1252  )         - initialized variables (global, static) in RAM/HEAP
RODATA : 1992  ) / 81920 - constants             (global, static) in RAM/HEAP
BSS    : 25400 )         - zeroed variables      (global, static) in RAM/HEAP

**Comment by Juerd** [comment]
A thought: for RAM savings, it might be interesting to allow putting the settings in a lambda, and call that once at startup and once when loading the portal, and dump the params vector in between. Especially those description strings can be large.

**Comment by Juerd** [comment]
Released as v3.5.4

**Comment by d-a-v** [comment]
Thanks !

**Pull request closed without merging**
